# Redpanda Connect (official redpanda/connect chart)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.redpanda.com
    chart: connect
    targetRevision: "${chart_version}"
    helm:
      releaseName: redpanda-connect
      values: |
        ${user_values_yaml}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${namespace}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
